/*
██████  ██ ███    ██  ██████      ███████ ████████  ██████  ██████   █████   ██████  ███████ 
██   ██ ██ ████   ██ ██    ██     ██         ██    ██    ██ ██   ██ ██   ██ ██       ██      
██   ██ ██ ██ ██  ██ ██    ██     ███████    ██    ██    ██ ██████  ███████ ██   ███ █████   
██   ██ ██ ██  ██ ██ ██    ██          ██    ██    ██    ██ ██   ██ ██   ██ ██    ██ ██      
██████  ██ ██   ████  ██████      ███████    ██     ██████  ██   ██ ██   ██  ██████  ███████ 
*/
//Storage for all my dinosaurs! Keeps all their data in one place.
//Emojis go here:💯🐟🥩🐐🐄🧍🌿🌳⭐💀

//TODO: For a future implementation, VERSION number would be a cool field for dinos.
const dinoArray = [
  {
    productName: "Allosaurus",
    latinName: "Different Lizard",
    imageName1: "Allo001.png",
    imageName2: "Allo002.png",
    imageName3: "Allo003.png",
    manufacturer: "Biosyn",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Carnivore", //🥩 🐐
    size: "Large",
    length: "12.01 m",
    height: "4.02 m",
    weight: "2086 kg",
    difficulty: "⭐⭐⭐⭐",
    price: 1873000,
    description:
      "Allosaurus was originally intended to be displayed as an attraction in Jurassic Park on Isla Nublar. However, they hadn't been cloned at the time of the 1993 incident, with a 1996 asset catalogue of the dinosaurs present on Nublar and InGen's Site B facility on Isla Sorna, reported that a mere twelve percent of the Allosaurus genome had been completed.",
  },
  {
    productName: "Ankylosaurus",
    latinName: "Fused Lizard",
    imageName1: "Anky003.jpg",
    imageName2: "Anky001.png",
    imageName3: "Anky002.jpg",
    manufacturer: "InGen",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Medium",
    length: "7.87 m",
    height: "2.78 m",
    weight: "5442 kg",
    difficulty: "⭐⭐⭐",
    price: 315000,
    description:
      "Ankylosaurus was one of the dinosaurs planned for the original Jurassic Park after its initial opening, with InGen having acquired 91% of the Ankylosaurus genome by 1993.[1] In 1999, after Masrani Global acquired InGen in the wake of the disastrous San Diego Incident, InGen scientists illegally conducted cloning experiments on Isla Sorna, where they bred Ankylosaurus as well as Spinosaurus, Corythosaurus, and Ceratosaurus. These Ankylosaurus were later released into the wild and were briefly encountered by the survivors of a plane crash on the island in 2001.",
  },
  {
    productName: "Apatosaurus",
    latinName: "Deceptive Lizard",
    imageName1: "Apato001.jpg",
    imageName2: "Apato002.jpg",
    imageName3: "Apato004.png",
    manufacturer: "Regenesis",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Herbivore", //🌿 🌳
    size: "Large",
    length: "24.3 m",
    height: "6.72 m",
    weight: "2086 kg",
    difficulty: "⭐⭐⭐",
    price: 851000,
    description:
      "Apatosaurus was originally planned to be exhibited as an attraction for the original Jurassic Park on Isla Nublar, with 57% of the genome completed by InGen by 1993. However, after the disastrous San Diego Incident, InGen was acquired by Masrani Global, which began development of Jurassic World on Nublar. Apatosaurus was eventually cloned and exhibited on the island, where it lived alongside numerous other species of herbivore such as Triceratops, Stegosaurus, and Parasaurolophus.",
  },
  {
    productName: "Baryonyx",
    latinName: "Heavy Claw",
    imageName1: "Bary001.jpg",
    imageName2: "Bary002.png",
    imageName3: "Bary003.png",
    manufacturer: "Regenesis",
    era: "Early Cretaceous",
    dna: "💯",
    diet: "Carnivore", //🥩 🐟
    size: "Large",
    length: "9.19 m",
    height: "2.74 m",
    weight: "907 kg",
    difficulty: "⭐⭐⭐⭐",
    price: 742000,
    description:
      "Originating in the early Cretaceous period, InGen bred a total of five Baryonyx specimens at their Site B facility on Isla Sorna, intending them for display at Jurassic Park on the neighbouring Isla Nublar. While an enclosure was prepared for the Baryonyx, no specimens were present on Isla Nublar during the fateful 1993 incident which resulted in the park's abandonment.",
  },
  {
    productName: "Brachiosaurus",
    latinName: "Arm Lizard",
    imageName1: "Brachy001.jpg",
    imageName2: "Brachy002.png",
    imageName3: "Brachy003.jpg",
    manufacturer: "InGen",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Herbivore", //🌳
    size: "Large",
    length: "18.77 m",
    height: "16.11 m",
    weight: "49855 kg",
    difficulty: "⭐⭐⭐⭐",
    price: 784000,
    description:
      "Originating in the Jurassic period, Brachiosaurus was the first species of sauropod bred by InGen for the original Jurassic Park on Isla Nublar. By the time of the Isla Nublar Incident in 1993, InGen had a herd of six Brachiosaurus in Jurassic Park, and ten on Isla Sorna. In an InGen report in 1996, it was reported that one Brachiosaurus died on Isla Nublar of malnutrition and that the original herd did not stray far from their enclosure, despite failed efforts by the island's Tyrannosaurus to hunt them.",
  },
  {
    productName: "Carnotaurus",
    latinName: "Meat Eating Bull",
    imageName1: "Carno001.jpg",
    imageName2: "Carno002.png",
    imageName3: "Carno004.jpg",
    manufacturer: "Biosyn",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Carnivore", //🥩 🐐 🐄 🧍
    size: "Large",
    length: "10.38 m",
    height: "4.05 m",
    weight: "1814 kg",
    difficulty: "⭐⭐⭐⭐⭐",
    price: 1384000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Ceratosaurus",
    latinName: "Horned Lizard",
    imageName1: "Cera001.jpg",
    imageName2: "Cera002.jpg",
    imageName3: "Cera003.png",
    manufacturer: "Biosyn",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Carnivore", //🥩 🐐 🐄 🧍
    size: "Large",
    length: "9 m",
    height: "3.75 m",
    weight: "907 kg",
    difficulty: "⭐⭐⭐⭐",
    price: 550000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Compsognathus",
    latinName: "Elegant Jaw",
    imageName1: "Compy001.png",
    imageName2: "Compy002.png",
    imageName3: "Compy003.png",
    manufacturer: "InGen",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Carnivore", //🥩
    size: "Small",
    length: "1 m",
    height: "0.41 m",
    weight: "2 kg",
    difficulty: "⭐⭐",
    price: 95000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Deinonychus",
    latinName: "Terrible Claw",
    imageName1: "Deino001.jpg",
    imageName2: "Deino002.png",
    imageName3: "Deino003.png",
    manufacturer: "Biosyn",
    era: "Early Cretaceous",
    dna: "💯",
    diet: "Carnivore", //🥩 🐐
    size: "Small",
    length: "3.19 m",
    height: "1.60 m",
    weight: "280 kg",
    difficulty: "⭐⭐⭐",
    price: 446000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Dilophosaurus",
    latinName: "Two-Crested Lizard",
    imageName1: "Dilo001.png",
    imageName2: "Dilo002.jpg",
    imageName3: "Dilo003.jpg",
    manufacturer: "InGen",
    era: "Early Jurassic",
    dna: "💯",
    diet: "Carnivore", //🥩 🐐
    size: "Small",
    length: "3.06 m",
    height: "1.61 m",
    weight: "300 kg",
    difficulty: "⭐⭐⭐",
    price: 317000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Diplodocus",
    latinName: "Double Beam",
    imageName1: "Diplo001.jpg",
    imageName2: "Diplo002.png",
    imageName3: "Diplo003.png",
    manufacturer: "Regensis",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Herbivore", //🥩 🐐
    size: "Large",
    length: "29.01 m",
    height: "5.93 m",
    weight: "14512 kg",
    difficulty: "⭐⭐⭐",
    price: 625000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Dryosaurus",
    latinName: "Tree Lizard",
    imageName1: "Dryo001.jpg",
    imageName2: "Dryo002.jpg",
    imageName3: "Dryo003.png",
    manufacturer: "InGen",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Small",
    length: "4.98 m",
    height: "1.83 m",
    weight: "80 kg",
    difficulty: "⭐⭐",
    price: 25000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Gallimimus",
    latinName: "Chicken Mimic",
    imageName1: "Galli001.jpg",
    imageName2: "Galli002.jpg",
    imageName3: "Galli003.jpg",
    manufacturer: "InGen",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿🌳
    size: "Medium",
    length: "4.61 m",
    height: "3.01 m",
    weight: "400 kg",
    difficulty: "⭐⭐",
    price: 80000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Herrerasaurus",
    latinName: "Herrera's Lizard",
    imageName1: "Herre001.jpg",
    imageName2: "Herre002.jpg",
    imageName3: "Herre003.png",
    manufacturer: "Regensis",
    era: "Triassic",
    dna: "💯",
    diet: "Carnivore", //🌿🌳
    size: "Medium",
    length: "6.20 m",
    height: "1.96 m",
    weight: "350 kg",
    difficulty: "⭐⭐⭐",
    price: 480000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Homocephale",
    latinName: "Even Head",
    imageName1: "Homo003.jpg",
    imageName2: "Homo002.png",
    imageName3: "Homo001.jpg",
    manufacturer: "Biosyn",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿🌳
    size: "Small",
    length: "2.29 m",
    height: "0.87 m",
    weight: "43 kg",
    difficulty: "⭐⭐",
    price: 130000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Iguanodon",
    latinName: "Iguana Tooth",
    imageName1: "Iguano001.jpg",
    imageName2: "Iguano002.jpg",
    imageName3: "Iguano003.jpg",
    manufacturer: "Biosyn",
    era: "Early Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿🌳
    size: "Large",
    length: "11.96 m",
    height: "4.26 m",
    weight: "3500 kg",
    difficulty: "⭐⭐⭐",
    price: 300000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Kentrosaurus",
    latinName: "Sharp Lizard",
    imageName1: "Kentro001.jpg",
    imageName2: "Kentro002.png",
    imageName3: "Kentro003.png",
    manufacturer: "Biosyn",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Medium",
    length: "8.84 m",
    height: "3.34 m",
    weight: "2721 kg",
    difficulty: "⭐⭐⭐",
    price: 310000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Olorotitan",
    latinName: "Gigantic Swan",
    imageName1: "Oloro001.jpg",
    imageName2: "Oloro002.jpg",
    imageName3: "Oloro003.jpg",
    manufacturer: "Regensis",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Large",
    length: "10.09 m",
    height: "4.27 m",
    weight: "3174 kg",
    difficulty: "⭐⭐⭐",
    price: 175000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Ouranosaurus",
    latinName: "Courageous Lizard",
    imageName1: "Ourano001.jpg",
    imageName2: "Ourano002.jpg",
    imageName3: "Ourano003.png",
    manufacturer: "Biosyn",
    era: "Early Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Large",
    length: "7.98 m",
    height: "3.89 m",
    weight: "2400 kg",
    difficulty: "⭐⭐⭐",
    price: 215000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Pachycephalosaurus",
    latinName: "Thick-Headed Lizard",
    imageName1: "Pachy001.png",
    imageName2: "Pachy002.jpg",
    imageName3: "Pachy003.png",
    manufacturer: "InGen",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Medium",
    length: "4.46 m",
    height: "1.89 m",
    weight: "450 kg",
    difficulty: "⭐⭐⭐⭐",
    price: 195000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Parasaurolophus",
    latinName: "Near-Crested Lizard",
    imageName1: "Para001.png",
    imageName2: "Para002.jpg",
    imageName3: "Para003.jpg",
    manufacturer: "InGen",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿🌳
    size: "Large",
    length: "9.80 m",
    height: "3.67 m",
    weight: "2267 kg",
    difficulty: "⭐⭐",
    price: 180000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Pentaceratops",
    latinName: "Five-Horned Face",
    imageName1: "Penta001.jpg",
    imageName2: "Penta002.png",
    imageName3: "Penta004.jpg",
    manufacturer: "Regenesis",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore",
    size: "Large",
    length: "7.90 m",
    height: "5.16 m",
    weight: "4535 kg",
    difficulty: "⭐⭐⭐⭐",
    price: 350000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Pteranodon",
    latinName: "Toothless Wing",
    imageName1: "Pter004.jpg",
    imageName2: "Pter002.jpg",
    imageName3: "Pter003.jpg",
    manufacturer: "InGen",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Carnivore",
    size: "Medium",
    length: "5.87 m",
    height: "2.13 m",
    weight: "55 kg",
    difficulty: "⭐⭐⭐⭐⭐",
    price: 425000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Sauropelta",
    latinName: "Lizard Shield",
    imageName1: "Sauro001.jpg",
    imageName2: "Sauro002.jpg",
    imageName3: "Sauro003.png",
    manufacturer: "Regenesis",
    era: "Early Cretaceous",
    dna: "💯",
    diet: "Herbivore",
    size: "Medium",
    length: "7.97 m",
    height: "2.12 m",
    weight: "1360 kg",
    difficulty: "⭐⭐",
    price: 355000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Sinoceratops",
    latinName: "Horned Face from China",
    imageName1: "Sino001.png",
    imageName2: "Sino002.png",
    imageName3: "Sino003.jpg",
    manufacturer: "Regenesis",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🐟
    size: "Medium",
    length: "8.10 m",
    height: "3.19 m",
    weight: "4535 kg",
    difficulty: "⭐⭐⭐",
    price: 241000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Spinosaurus",
    latinName: "Spined Lizard",
    imageName1: "Spino001.png",
    imageName2: "Spino002.png",
    imageName3: "Spino003.jpg",
    manufacturer: "Biosyn",
    era: "Early Cretaceous",
    dna: "💯",
    diet: "Carnivore",
    size: "Large",
    length: "15 m",
    height: "6.38 m",
    weight: "18140 kg",
    difficulty: "⭐⭐⭐",
    price: 2012000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Stegosaurus",
    latinName: "Roofed Lizard",
    imageName1: "Stego001.png",
    imageName2: "Stego002.jpg",
    imageName3: "Stego003.jpg",
    manufacturer: "InGen",
    era: "Late Jurassic",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Large",
    length: "10.1 m",
    height: "4.93 m",
    weight: "3083 kg",
    difficulty: "⭐⭐⭐",
    price: 320000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Struthiomimus",
    latinName: "Ostrich Mimic",
    imageName1: "Struth001.png",
    imageName2: "Struth002.jpg",
    imageName3: "Struth003.png",
    manufacturer: "Regenesis",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Small",
    length: "4.28 m",
    height: "2.32 m",
    weight: "150 kg",
    difficulty: "⭐⭐",
    price: 30000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Stygimoloch",
    latinName: "Demon from the Styx",
    imageName1: "Styg001.png",
    imageName2: "Styg002.jpg",
    imageName3: "Styg003.png",
    manufacturer: "Regenesis",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Small",
    length: "3.53 m",
    height: "1.68 m",
    weight: "78 kg",
    difficulty: "⭐⭐⭐⭐",
    price: 188000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Styracosaurus",
    latinName: "Spiked Lizard",
    imageName1: "Styraco001.jpg",
    imageName2: "Styraco002.png",
    imageName3: "Styraco003.jpg",
    manufacturer: "Regenesis",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Large",
    length: "8.02 m",
    height: "4.10 m",
    weight: "2721 kg",
    difficulty: "⭐⭐⭐",
    price: 315000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Torosaurus",
    latinName: "Perforated Lizard",
    imageName1: "Toro001.png",
    imageName2: "Toro002.jpg",
    imageName3: "Toro003.jpg",
    manufacturer: "Biosyn",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Large",
    length: "7.90 m",
    height: "3.63 m",
    weight: "5442 kg",
    difficulty: "⭐⭐⭐⭐",
    price: 340000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Triceratops",
    latinName: "Three-Horned Face",
    imageName1: "Trike001.jpg",
    imageName2: "Trike002.jpg",
    imageName3: "Trike003.png",
    manufacturer: "InGen",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Herbivore", //🌿
    size: "Large",
    length: "9.90 m",
    height: "3.93 m",
    weight: "8163 kg",
    difficulty: "⭐⭐⭐",
    price: 230000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Troodon",
    latinName: "Wounding Tooth",
    imageName1: "Troo001.jpg",
    imageName2: "Troo002.jpg",
    imageName3: "Troo003.jpg",
    manufacturer: "Biosyn",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Carnivore", //🥩
    size: "Small",
    length: "3 m",
    height: "1.2 m",
    weight: "50 kg",
    difficulty: "⭐⭐⭐",
    price: 302000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Tyrannosaurus",
    latinName: "Tyrant Lizard King",
    imageName1: "Rex001.png",
    imageName2: "Rex002.jpg",
    imageName3: "Rex003.jpg",
    manufacturer: "InGen",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Carnivore", //🥩 🐐 🐄 🧍
    size: "Large",
    length: "13.5 m",
    height: "5.89 m",
    weight: "16326 kg",
    difficulty: "⭐⭐⭐⭐⭐",
    price: 1964000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    productName: "Velociraptor",
    latinName: "Different Lizard",
    imageName1: "Raptor002.png",
    imageName2: "Raptor002.jpg",
    imageName3: "Raptor003.png",
    manufacturer: "InGen",
    era: "Late Cretaceous",
    dna: "💯",
    diet: "Carnivore", //🥩 🐐 🐄 🧍
    size: "Medium",
    length: "3.96 m",
    height: "1.73 m",
    weight: "150 kg",
    difficulty: "💀",
    price: 373000,
    cardDescription: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];
